# Generated by Django 5.1.15 on 2026-09-23 17:20

import uuid

import api.rls
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0098_tenant_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="manage_triage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="manage_triage_exceptions",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FindingTriage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding_uid", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("remediating", "Remediating"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                            ("risk_accepted", "Risk Accepted"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("last_result", models.CharField(blank=True, max_length=4)),
                ("last_scan_id", models.UUIDField(blank=True, null=True)),
                ("last_scan_started_at", models.DateTimeField(blank=True, null=True)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.provider"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finding_triages",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingTriageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("changes", models.JSONField(default=dict)),
                ("scan_id", models.UUIDField(blank=True, null=True)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
                (
                    "triage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.findingtriage",
                    ),
                ),
            ],
            options={
                "db_table": "finding_triage_events",
                "ordering": ["-inserted_at", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingTriageNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.CharField(max_length=500)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
                (
                    "triage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note",
                        to="api.findingtriage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finding_triage_notes",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="findingtriage",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "provider", "finding_uid"),
                name="unique_provider_finding_triage",
            ),
        ),
        migrations.AddConstraint(
            model_name="findingtriage",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_findingtriage",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
        migrations.AddConstraint(
            model_name="findingtriageevent",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_findingtriageevent",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
        migrations.AddConstraint(
            model_name="findingtriagenote",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_findingtriagenote",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ]
