# Generated by Django 5.1.15 on 2026-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0100_triage_managed_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingtriage",
            name="observation",
            field=models.CharField(default="observed", max_length=32),
        ),
        migrations.AddField(
            model_name="findingtriage",
            name="observation_detail",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="findingtriage",
            name="observation_scan_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="findingtriage",
            name="resolution_reason",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="findingtriage",
            name="snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="findingtriage",
            name="verification_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
