# Generated by Django 5.1.15 on 2026-09-25 19:23

import api.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0101_triage_tracking"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TYPE severity ADD VALUE IF NOT EXISTS 'unknown' AFTER 'informational';",
        ),
        migrations.AddField(
            model_name="dailyseveritysummary",
            name="unknown",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="finding",
            name="impact",
            field=api.db_utils.SeverityEnumField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("informational", "Informational"),
                    ("unknown", "Unknown"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="severity",
            field=api.db_utils.SeverityEnumField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("informational", "Informational"),
                    ("unknown", "Unknown"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="scancategorysummary",
            name="severity",
            field=api.db_utils.SeverityEnumField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("informational", "Informational"),
                    ("unknown", "Unknown"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="scangroupsummary",
            name="severity",
            field=api.db_utils.SeverityEnumField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("informational", "Informational"),
                    ("unknown", "Unknown"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="scansummary",
            name="severity",
            field=api.db_utils.SeverityEnumField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("informational", "Informational"),
                    ("unknown", "Unknown"),
                ]
            ),
        ),
    ]
